### ISSUE TITLE
Cleanroom to Magellan procedure revisions

### ISSUE THREAD

**Issue by joseph-long** [magao-x/handbook#9]

**Comment by joseph-long** [comment]
Ordering of adding cart to table: position table under crane before completing the cart, since moving the table legs and cart has a tendency to jam one on the other.

**Comment by joseph-long** [comment]
Hook carabiners to cart with open side up (so the cables can reach load spreader)

(Have pic)

**Comment by joseph-long** [comment]
More long handled large Allen keys to parallelize cart (dis)assembly

**Comment by joseph-long** [comment]
Request additional hook on Isuzu just forward of rear wheel fender

**Comment by joseph-long** [comment]
Ordering: legs must reach nasmyth platform before instrument, else instrument would be in the way on platform

**Comment by joseph-long** [comment]
Corner clamps B and C are “telescope side” on the table. Note clamp indexing != leg indexing

**Comment by joseph-long** [comment]
Table gimbal misalignment upon lowering the table is an issue. Possible solutions include extreme care with crane operation, or maybe lowering by crane onto screw jacks for final lowering by hand

**Comment by jaredmales** [comment]
how are we doing on these?

**Comment by joseph-long** [comment]
get outta here, everyone knows the procedure now
